dist: xenial
sudo: required

language: c

os:
    - linux
    - osx
    - windows

compiler:
    - gcc
    - clang

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

matrix:
    exclude:
        - os: osx
          compiler: gcc
        - os: windows
          compiler: clang

install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
    - source "${TRAVIS_BUILD_DIR}/ci/travis/install-${TRAVIS_OS_NAME}.sh"
    - cd "${TRAVIS_BUILD_DIR}"

script:
    - mkdir build
    - cd build
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
          GENERATOR="MinGW Makefiles";
      else
          GENERATOR="Unix Makefiles";
      fi
    - cmake -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DBUILD_TEST=1 -G "$GENERATOR" ..
    - cmake --build .
    - ctest -V

