#ifndef CONSTS_H_
#define CONSTS_H_

#define HOMEL_VERSION "1.0"

#define MAX_STRING_LEN 1024

#define PRINT_TABLE_FIRST_COL_SIZE 4
#define PRINT_TABLE_SECOND_COL_SIZE 28
#define PRINT_TABLE_THIRD_COL_SIZE 28

#define READ_TPATHES_MAX_COUNT 128

#endif /* !CONSTS_H_ */
